version: 2
updates:
  # ---------- GitHub Actions ----------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "GitHubSecurityLab/codeql-community-packs-admin"
    target-branch: "main"
    commit-message:
      prefix: deps
      prefix-development: chore
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
