#!/usr/bin/env bash
# Builds a markdown table summarizing the package versions produced by a
# publish.yml run, from the per-job JSON result fragments it wrote.
#
# Usage: build-publish-summary.sh <results-dir>
#
# Each fragment in <results-dir> looks like:
#   {
#     "language": "cpp",
#     "type": "src",
#     "package": "codeql-cpp-queries",
#     "previous_version": "0.2.1",
#     "target_version": "0.2.2",
#     "status": "published"   # published | up-to-date | failed
#   }
set -euo pipefail

RESULTS_DIR="${1:?usage: build-publish-summary.sh <results-dir>}"
REPO="${GITHUB_REPOSITORY:-GitHubSecurityLab/CodeQL-Community-Packs}"
RUN_URL="${GITHUB_SERVER_URL:-https://github.com}/${REPO}/actions/runs/${GITHUB_RUN_ID:-}"

shopt -s nullglob
FRAGMENTS=("$RESULTS_DIR"/*.json)
if [ "${#FRAGMENTS[@]}" -eq 0 ]; then
  MERGED='[]'
else
  MERGED=$(jq -s '.' "${FRAGMENTS[@]}")
fi

LANGUAGES=(cpp csharp go java javascript python ruby)
TYPES=(src lib ext ext-library-sources)
EXT_LANGUAGES=(csharp java)

lang_label() {
  case "$1" in
    cpp) echo "C++" ;;
    csharp) echo "C#" ;;
    go) echo "Go" ;;
    java) echo "Java" ;;
    javascript) echo "JavaScript" ;;
    python) echo "Python" ;;
    ruby) echo "Ruby" ;;
    *) echo "$1" ;;
  esac
}

is_ext_language() {
  local lang="$1"
  for l in "${EXT_LANGUAGES[@]}"; do
    [ "$l" == "$lang" ] && return 0
  done
  return 1
}

cell() {
  local lang="$1" type="$2"
  local entry
  entry=$(echo "$MERGED" | jq -c --arg l "$lang" --arg t "$type" \
    '[.[] | select(.language == $l and .type == $t)] | first // empty')

  if [ -z "$entry" ] || [ "$entry" == "null" ]; then
    # This combo is expected to publish (unlike the "n/a" combos filtered out
    # by the caller) but no result fragment was found for it.
    echo "❓ no result"
    return
  fi

  local package version status previous
  package=$(echo "$entry" | jq -r '.package')
  version=$(echo "$entry" | jq -r '.target_version')
  status=$(echo "$entry" | jq -r '.status')
  previous=$(echo "$entry" | jq -r '.previous_version')
  local url="https://github.com/${REPO}/pkgs/container/${package}?tag=${version}"

  case "$status" in
    published)  echo "[${version}](${url}) 🆕" ;;
    up-to-date) echo "[${version}](${url})" ;;
    failed)     echo "⚠️ publish failed (still \`${previous}\`)" ;;
    *)          echo "❓ unknown" ;;
  esac
}

echo "## Publish summary"
echo
echo "_Generated by [publish.yml run #${GITHUB_RUN_NUMBER:-}](${RUN_URL}) — 🆕 marks a package republished by this run._"
echo
echo "| Language | Queries (\`src\`) | Library (\`lib\`) | Extensions (\`ext\`) | Library sources (\`ext-library-sources\`) |"
echo "| --- | --- | --- | --- | --- |"
for lang in "${LANGUAGES[@]}"; do
  row="| $(lang_label "$lang") |"
  for type in "${TYPES[@]}"; do
    if { [ "$type" == "ext" ] || [ "$type" == "ext-library-sources" ]; } && ! is_ext_language "$lang"; then
      row="$row n/a |"
      continue
    fi
    row="$row $(cell "$lang" "$type") |"
  done
  echo "$row"
done
