#!/bin/bash
set -euo pipefail

# Generates a Markdown table of every pack's published (GHCR) version next
# to its local qlpack.yml version, so there's a single place to answer
# "what's live?" without paging through the GHCR Packages UI or grepping
# every qlpack.yml by hand (see CONTRIBUTING.md § How packages get
# published).
#
# Usage: generate-version-inventory.sh > PACKAGE_VERSIONS.md

LANGUAGES=(cpp csharp go java javascript python ruby)

# subdir -> (GHCR package suffix, human label)
declare -A PACKAGE_SUFFIX=(
    [src]="queries"
    [lib]="libs"
    [ext]="extensions"
    [ext-library-sources]="library-sources"
)
declare -A SUBDIR_LABEL=(
    [src]="Queries (src)"
    [lib]="Library (lib)"
    [ext]="Extensions (ext)"
    [ext-library-sources]="Library sources (ext-library-sources)"
)

echo "<!-- Generated by .github/scripts/generate-version-inventory.sh - do not edit by hand. -->"
echo "# Published package versions"
echo
echo "This table is regenerated on a schedule by [\`publish-version-inventory.yml\`](./.github/workflows/publish-version-inventory.yml)."
echo "\"Published\" is what's currently live on [GHCR](https://github.com/orgs/GitHubSecurityLab/packages?repo_name=CodeQL-Community-Packs)."
echo "\"On main\" is the version declared in that pack's \`qlpack.yml\` on the default branch - if it differs from"
echo "\"Published\", that version will be published the next time \`main\` is pushed to (see [publish.yml](./.github/workflows/publish.yml))."
echo
echo "| Language | Pack | Published | On main | Package |"
echo "| --- | --- | --- | --- | --- |"

for language in "${LANGUAGES[@]}"; do
    for subdir in src lib ext ext-library-sources; do
        qlpack_path="$language/$subdir/qlpack.yml"
        if [[ ! -f "$qlpack_path" ]]; then
            continue
        fi

        package="codeql-$language-${PACKAGE_SUFFIX[$subdir]}"
        current_version=$(grep '^version:' "$qlpack_path" | awk '{print $2}' | tr -d '"'\''')
        published_version=$(gh api "/orgs/githubsecuritylab/packages/container/$package/versions" --jq '.[0].metadata.container.tags[0]' 2>/dev/null || echo "_none_")

        echo "| $language | ${SUBDIR_LABEL[$subdir]} | \`$published_version\` | \`$current_version\` | [\`$package\`](https://github.com/GitHubSecurityLab/CodeQL-Community-Packs/pkgs/container/$package) |"
    done
done
