name: "CodeQL Community Packs"
default: false

locations:
  - name: "CodeQL Packs"
    paths:
      - "**/qlpack.yml"
    patterns:
      - version:\s*([0-9]+\.[0-9]+\.[0-9])

  - name: "CodeQL Pack Libaries"
    paths:
      - "**/qlpack.yml"
    patterns:
      - githubsecuritylab/codeql-[a-zA-Z]*-libs:\s*([0-9]+\.[0-9]+\.[0-9])

