extensions:
  - addsTo:
      pack: codeql/csharp-all
      extensible: sourceModel
    data:
      - ["Voron.Util.Settings", "PathSettingBase<>", False, "PathSettingBase", "(System.String,Voron.Util.Settings.PathSettingBase<>)", "", "Parameter[0]", "remote", "manual"]