extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["io.prometheus.client.exporter.common", "TextFormat", True, "chooseContentType", "(String)", "", "Parameter[0]", "remote", "manual"]