extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["org.apache.http.client.config", "RequestConfig$Builder", True, "setSocketTimeout", "(int)", "", "Parameter[0]", "remote", "manual"]
      - ["org.apache.http.client.config", "RequestConfig$Builder", True, "setRedirectsEnabled", "(boolean)", "", "Parameter[0]", "remote", "manual"]
      - ["org.apache.http.client.config", "RequestConfig$Builder", True, "setConnectTimeout", "(int)", "", "Parameter[0]", "remote", "manual"]