extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["io.swagger.sam.client", "ApiClient", True, "setAccessToken", "(String)", "", "Parameter[0]", "remote", "manual"]