extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["org.apache.sshd.common.config.keys", "AuthorizedKeyEntry", True, "readAuthorizedKeys", "(Reader,boolean)", "", "Parameter[0]", "remote", "manual"]