extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["com.orientechnologies.orient.core.config", "OStorageClusterConfiguration$STATUS", False, "valueOf", "(String)", "", "Parameter[0]", "remote", "manual"]