extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["io.prometheus.client.exporter", "PushGateway", True, "push", "(CollectorRegistry,String,Map)", "", "Parameter[2]", "remote", "manual"]
      - ["io.prometheus.client.exporter", "PushGateway", True, "push", "(CollectorRegistry,String,Map)", "", "Parameter[1]", "remote", "manual"]