extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["io.syndesis.server.api.generator.openapi", "OpenApiPropertyGenerator<Oas30Document,Oas30SecurityScheme>", True, "createProperty", "(String,OpenApiModelInfo,ConfigurationProperty,ConnectorSettings)", "", "Parameter[3]", "remote", "manual"]
      - ["io.syndesis.server.api.generator.openapi", "OpenApiPropertyGenerator<Oas20Document,Oas20SecurityScheme>", True, "createProperty", "(String,OpenApiModelInfo,ConfigurationProperty,ConnectorSettings)", "", "Parameter[3]", "remote", "manual"]