extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["javafx.application", "Platform", False, "runLater", "(Runnable)", "", "Parameter[0]", "remote", "manual"]