extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["org.opennms.netmgt.config.threshd", "FilterOperator", False, "valueOf", "(String)", "", "Parameter[0]", "remote", "manual"]