extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["org.infinispan.client.hotrod.configuration", "RemoteCacheConfigurationBuilder", True, "configurationURI", "(URI)", "", "Parameter[0]", "remote", "manual"]