extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["org.apache.pinot.spi.config.tenant", "TenantRole", False, "valueOf", "(String)", "", "Parameter[0]", "remote", "manual"]