extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["password.pwm.http.servlet.configeditor", "ReadSettingResponse$ReadSettingResponseBuilder", True, "key", "(String)", "", "Parameter[0]", "remote", "manual"]