extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["password.pwm.config.value.data", "FormConfiguration", False, "checkValue", "(DomainConfig,String,Locale)", "", "Parameter[1]", "remote", "manual"]