extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["com.thoughtworks.go.config", "PluginProfiles<SecurityAuthConfig>", True, "findByPluginId", "(String)", "", "Parameter[0]", "remote", "manual"]