extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["com.alibaba.dubbo.config", "ReferenceConfig<GenericService>", True, "setInterface", "(String)", "", "Parameter[0]", "remote", "manual"]