extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["io.swagger.v3.parser.util", "RemoteUrl", True, "urlToString", "(String,List)", "", "Parameter[0]", "remote", "manual"]
      - ["io.swagger.v3.parser.util", "DeserializationUtils", True, "readYamlTree", "(String)", "", "Parameter[0]", "remote", "manual"]