extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["io.swagger.parser.util", "DeserializationUtils", True, "readYamlTree", "(String,SwaggerDeserializationResult)", "", "Parameter[0]", "remote", "manual"]