extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["org.apache.druid.common.config", "ConfigManager$ConfigHolder<>", True, "swapIfNew", "(byte[])", "", "Parameter[0]", "remote", "manual"]