extensions:
  - addsTo:
      pack: codeql/java-all
      extensible: sourceModel
    data:
      - ["password.pwm.config.option", "IdentityVerificationMethod", False, "valueOf", "(String)", "", "Parameter[0]", "remote", "manual"]